### ISSUE TITLE
about generateProgressBar Generation error problem

### ISSUE THREAD

**Issue by Chendaqian** [liununu/liununu#6]
```javascript
2023-06-08T04:19:36.3103902Z SyntaxError: Unexpected end of input
2023-06-08T04:19:36.3104278Z     at wrapSafe (internal/modules/cjs/loader.js:1029:16)
2023-06-08T04:19:36.3104651Z     at Module._compile (internal/modules/cjs/loader.js:1078:27)
2023-06-08T04:19:36.3105075Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
2023-06-08T04:19:36.3105476Z     at Module.load (internal/modules/cjs/loader.js:979:32)
2023-06-08T04:19:36.3105867Z     at Function.Module._load (internal/modules/cjs/loader.js:819:12)
2023-06-08T04:19:36.3106400Z     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
2023-06-08T04:19:36.3106791Z     at internal/main/run_main_module.js:17:47
2023-06-08T04:19:36.3212287Z ##[error]Process completed with exit code 1.
``` 
https://pipelines.actions.githubusercontent.com/serviceHosts/1ce782a6-f2b7-45d4-9f40-c36f4b217834/_apis/pipelines/1/runs/32/signedlogcontent/2?urlExpires=2023-06-08T04%3A20%3A47.4159435Z&urlSigningMethod=HMACV1&urlSignature=U6sBzC8gSkt1HjAwct%2Bk6Rk7rtN5MIG%2FgmjX4OhoeI4%3D

How to solve the above error?

This is my github address  https://github.com/ChenDaqian/ChenDaqian

**Comment by Chendaqian** [comment]
> ```js
> 2023-06-08T04:19:36.3103902Z SyntaxError: Unexpected end of input
> 2023-06-08T04:19:36.3104278Z     at wrapSafe (internal/modules/cjs/loader.js:1029:16)
> 2023-06-08T04:19:36.3104651Z     at Module._compile (internal/modules/cjs/loader.js:1078:27)
> 2023-06-08T04:19:36.3105075Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
> 2023-06-08T04:19:36.3105476Z     at Module.load (internal/modules/cjs/loader.js:979:32)
> 2023-06-08T04:19:36.3105867Z     at Function.Module._load (internal/modules/cjs/loader.js:819:12)
> 2023-06-08T04:19:36.3106400Z     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
> 2023-06-08T04:19:36.3106791Z     at internal/main/run_main_module.js:17:47
> 2023-06-08T04:19:36.3212287Z ##[error]Process completed with exit code 1.
> ```
> 
> https://pipelines.actions.githubusercontent.com/serviceHosts/1ce782a6-f2b7-45d4-9f40-c36f4b217834/_apis/pipelines/1/runs/32/signedlogcontent/2?urlExpires=2023-06-08T04%3A20%3A47.4159435Z&urlSigningMethod=HMACV1&urlSignature=U6sBzC8gSkt1HjAwct%2Bk6Rk7rtN5MIG%2FgmjX4OhoeI4%3D
> 
> How to solve the above error?
> 
> This is my github address https://github.com/ChenDaqian/ChenDaqian
